### ISSUE TITLE
LoginSessionActor dies upon bad match

### ISSUE THREAD

**Issue by pschord** [psforever/PSF-LoginServer#10]
SessionRouter or some session specific parent needs to watch child Actors for death events and appropriately restart them.

```
2016-05-01 23:28:40,326 ERROR [PsLogin-akka.actor.default-dispatcher-10 sessionId=none] akka.actor.OneForOneStrategy - MultiPacket(Vector(ByteVector(62 bytes, 0x0009000403895053466f72657665720000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000), ByteVector(62 bytes, 0x0009000203895053466f72657665720000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000))) (of class psforever.net.MultiPacket)
scala.MatchError: MultiPacket(Vector(ByteVector(62 bytes, 0x0009000403895053466f72657665720000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000), ByteVector(62 bytes, 0x0009000203895053466f72657665720000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000))) (of class psforever.net.MultiPacket)
        at LoginSessionActor.handleControlPkt(LoginSessionActor.scala:37)
        at LoginSessionActor$$anonfun$Started$1.applyOrElse(LoginSessionActor.scala:30)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:482)
        at LoginSessionActor.akka$actor$MDCContextAware$$super$aroundReceive(LoginSessionActor.scala:9)
        at akka.actor.MDCContextAware$class.aroundReceive(MDCContextAware.scala:25)
        at LoginSessionActor.aroundReceive(LoginSessionActor.scala:9)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2016-05-01 23:28:41,148 ERROR [PsLogin-akka.actor.default-dispatcher-31 sessionId=2] CryptoSessionActor - Failed to decode encrypted packet: Failed to parse control packet 0x09: unknown: expected constant BitVector(8 bits, 0x00) but got BitVector(8 bits, 0x03)
2016-05-01 23:28:42,041 ERROR [PsLogin-akka.actor.default-dispatcher-30 sessionId=2] CryptoSessionActor - Failed to decode encrypted packet: Failed to parse control packet 0x09: unknown: expected constant BitVector(8 bits, 0x00) but got BitVector(8 bits, 0x01)
2016-05-01 23:28:42,773 ERROR [PsLogin-akka.actor.default-dispatcher-31 sessionId=none] LoginSessionActor - Unknown message
2016-05-01 23:28:43,743 ERROR [PsLogin-akka.actor.default-dispatcher-31 sessionId=2] CryptoSessionActor - Failed to decode encrypted packet: Failed to parse control packet 0x09: unknown: expected constant BitVector(8 bits, 0x00) but got BitVector(8 bits, 0x04)
2016-05-01 23:28:43,885 ERROR [PsLogin-akka.actor.default-dispatcher-33 sessionId=2] CryptoSessionActor - Failed to decode encrypted packet: Failed to parse control packet 0x09: unknown: expected constant BitVector(8 bits, 0x00) but got BitVector(8 bits, 0x02)
2016-05-01 23:28:44,837 ERROR [PsLogin-akka.actor.default-dispatcher-33 sessionId=2] CryptoSessionActor - Failed to decode encrypted packet: Failed to parse control packet 0x09: unknown: expected constant BitVector(8 bits, 0x00) but got BitVector(8 bits, 0x03)
2016-05-01 23:28:45,851 ERROR [PsLogin-akka.actor.default-dispatcher-22 sessionId=2] CryptoSessionActor - Failed to decode encrypted packet: Failed to parse control packet 0x09: unknown: expected constant BitVector(8 bits, 0x00) but got BitVector(8 bits, 0x01)
2016-05-01 23:28:46,715 INFO  [PsLogin-akka.actor.default-dispatcher-33 sessionId=none] akka.actor.LocalActorRef - Message [psforever.net.ControlPacket] from Actor[akka://PsLogin/user/session-router/crypto-session2#1836272772] to Actor[akka://PsLogin/user/session-router/login-session2#-143057463] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```

**Comment by pschord** [comment]
Fixed by cdf240c
