### ISSUE TITLE
No Owner Complaint

### ISSUE THREAD

**Issue by Fate-JH** [psforever/PSF-LoginServer#1228]
An infrequently frequently startup issue:
```
[ WARN] Amenity - Amenity <GUID> in zone <ZONE> tried to access owner, but doesn't have one.
```
... where a variety of amenities belonging to a single zone will produce this report shortly after the server should have fully started.  The zone changes but frequently involves the battle islands and never features more than one.  This might be lingering startup messages that were added late to the log but the fact that they occur at all in concerning.  Should be able to find detailed examples in server logs an aborted around start-up (the shortest ones especially).

Most likely, the result of an asyncrhonous action that should be gated being start-up set-up.

**Comment by ScrawnyRonnie** [comment]
Each time I see this, the GUIDs in question are always manned_turrets. I've also seen this different error:

`WARN Amenity - Amenity ValidPlanetSideGUID(369) tried to access it's Zone, but doesn't have one.`

Additional errors about these turrets sometimes also show after these warnings:

`[ERROR] akka.actor.SupervisorStrategy - did not initialize this object net.psforever.objects.serverobject.turret.FacilityTurret@3aab6ebd with a valid global identifier
akka.actor.ActorInitializationException: akka://PsLogin/user/interstellarCluster/zone-i4/manned_turret_194: exception during creation, root cause message: [did not initialize this object net.psforever.objects.serverobject.turret.FacilityTurret@3aab6ebd with a valid global identifier]
        at akka.actor.ActorInitializationException$.apply(Actor.scala:196)
        at akka.actor.ActorCell.create(ActorCell.scala:668)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:513)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:535)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:295)
        at akka.dispatch.Mailbox.run(Mailbox.scala:230)
        at kamon.instrumentation.executor.ExecutorInstrumentation$InstrumentedForkJoinPool$TimingRunnable.run(ExecutorInstrumentation.scala:698)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)`

If that happens, the turret doesn't work. It will not return fire and cannot be mounted. Example error trying to shoot broken turret:

`[ INFO] akka.actor.LocalActorRef - Message [net.psforever.objects.vital.Vitality$Damage] from Actor[akka://PsLogin/user/socketPane/world-socket-51001/middleware-09932888-8896-45d8-9fdb-1c1cf4d3c6cd/$a/session-e22e6ad2-a88a-4fa7-a2bd-38de1bb96b9f#-1367218741] to Actor[akka://PsLogin/user/interstellarCluster/zone-i4/manned_turret_195#-851849302] was not delivered. [1] dead letters encountered. If this is not an expected behavior then Actor[akka://PsLogin/user/interstellarCluster/zone-i4/manned_turret_195#-851849302] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.`

**Comment by Dethdeath** [comment]
A lot, if not all, tower wall turrets have ceased to work. They don't auto-fire at vehicles and don't fire back when taking damage. This is probably the cause.

**Comment by ScrawnyRonnie** [comment]
This is a best guess based on some testing... It seems like HART shuttles are victim to this underlying issue now as well after a recent update. While there isn't necessarily a warning logged, the same timing issue is seen. A recent report showed a HART shuttle that appeared to be NC landing in VS sanc. I did some local testing and forced the shuttles to have a faction of Neutral and doing this made them use the NC shuttle texture. Client decided NC as the fallback since there is no Neutral texture for these? The theory is the server is starting up the HART stuff before the zone setup is done and buildings are assigned their factions. & because the shuttle code is `newShuttle.Faction = pad.Faction` if the building has no owner yet, the pad has no owner yet, and no owner defaults these to Neutral.

How can we make the server not do stuff that relies on accurate ownership of things until it is done doing that?

**Comment by Fate-JH** [comment]
As to the shuttle, since the zone is a sanctuary, why not just assign the faction affiliation to the building or entity upon generation?  It should always be the same.

For turrets, they are more complicated.  Outlined above are different issues.  The "tried to access it's Zone, but doesn't have one" message originates from the amenity system.  It's literally a response to "_thing_.Zone" where both its zone and its owner's zones are set to `Nowhere`.  The "did not initialize this object" error is the message that is thrown if the GUID is left in its initial state of being unset.  It's literally a response to "_thing_.GUID".  This latter one is also very explicit about when the event is occurring - at the time of control actor creation (`ActorInitializationException`) - but the former one could happen at any point during the startup process.
