### ISSUE TITLE
Crash - Combat Engineering - Damaging a deployable cadaver crashes WSA

### ISSUE THREAD

**Issue by pschord** [psforever/PSF-LoginServer#324]
```2020-01-12 00:12:59,338  INFO "sessionId=7" WorldSessionActor - AvatarFirstTimeEvent: AvatarFirstTimeEventMessage(ValidPlanetSideGUID(3816),ValidPlanetSideGUID(7460),1,visited_motion_sensor)
2020-01-12 00:12:59,448  INFO "sessionId=7" WorldSessionActor - WeaponFire: WeaponFireMessage(355,ValidPlanetSideGUID(9829),ValidPlanetSideGUID(40113),Vector3(982.21094,1023.71094,100.875),0,446,63536,200,255,0,None)
2020-01-12 00:12:59,448  INFO "sessionId=7" WorldSessionActor - Hit: HitMessage(356,ValidPlanetSideGUID(40113),0,Some(HitInfo(Vector3(982.21094,1023.71094,100.875),Vector3(983.7422,1022.2344,100.515625),Some(ValidPlanetSideGUID(7460)))),true,false,None)
2020-01-12 00:12:59,606  INFO "sessionId=7" WorldSessionActor - WeaponFire: WeaponFireMessage(360,ValidPlanetSideGUID(9829),ValidPlanetSideGUID(40114),Vector3(982.2031,1023.71875,100.890625),0,486,63546,200,255,0,None)
2020-01-12 00:12:59,606  INFO "sessionId=7" WorldSessionActor - Hit: HitMessage(360,ValidPlanetSideGUID(40114),0,Some(HitInfo(Vector3(982.2031,1023.71875,100.890625),Vector3(983.75,1022.2422,100.5),Some(ValidPlanetSideGUID(7460)))),true,false,None)
2020-01-12 00:12:59,777  INFO "sessionId=7" WorldSessionActor - WeaponFire: WeaponFireMessage(365,ValidPlanetSideGUID(9829),ValidPlanetSideGUID(40115),Vector3(982.2031,1023.71875,100.890625),0,462,63549,200,255,0,None)
2020-01-12 00:12:59,777  INFO "sessionId=7" WorldSessionActor - Hit: HitMessage(365,ValidPlanetSideGUID(40115),0,Some(HitInfo(Vector3(982.2031,1023.71875,100.890625),Vector3(983.75,1022.2422,100.515625),Some(ValidPlanetSideGUID(7460)))),true,false,None)
2020-01-12 00:12:59,886  INFO "sessionId=7" WorldSessionActor - WeaponFire: WeaponFireMessage(370,ValidPlanetSideGUID(9829),ValidPlanetSideGUID(40116),Vector3(982.2031,1023.71875,100.890625),0,484,63574,200,255,0,None)
2020-01-12 00:12:59,886  INFO "sessionId=7" WorldSessionActor - Hit: HitMessage(370,ValidPlanetSideGUID(40116),0,Some(HitInfo(Vector3(982.2031,1023.71875,100.890625),Vector3(983.7656,1022.2578,100.5),Some(ValidPlanetSideGUID(7460)))),true,false,None)
2020-01-12 00:13:00,108  INFO "sessionId=7" WorldSessionActor - WeaponFire: WeaponFireMessage(375,ValidPlanetSideGUID(9829),ValidPlanetSideGUID(40117),Vector3(982.2031,1023.71875,100.890625),0,480,63569,200,255,0,None)
2020-01-12 00:13:00,108  INFO "sessionId=7" WorldSessionActor - Hit: HitMessage(375,ValidPlanetSideGUID(40117),0,Some(HitInfo(Vector3(982.2031,1023.71875,100.890625),Vector3(983.7578,1022.2578,100.5),Some(ValidPlanetSideGUID(7460)))),true,false,None)
2020-01-12 00:13:00,262  INFO "sessionId=7" WorldSessionActor - WeaponFire: WeaponFireMessage(380,ValidPlanetSideGUID(9829),ValidPlanetSideGUID(40118),Vector3(982.2031,1023.71875,100.890625),0,495,63594,200,255,0,None)
2020-01-12 00:13:00,262  INFO "sessionId=7" WorldSessionActor - Hit: HitMessage(380,ValidPlanetSideGUID(40118),0,Some(HitInfo(Vector3(982.2031,1023.71875,100.890625),Vector3(983.78125,1022.2656,100.484375),Some(ValidPlanetSideGUID(7460)))),true,false,None)
2020-01-12 00:13:00,404  INFO "sessionId=7" WorldSessionActor - WeaponFire: WeaponFireMessage(384,ValidPlanetSideGUID(9829),ValidPlanetSideGUID(40119),Vector3(982.2031,1023.71875,100.890625),0,495,63574,200,255,0,None)
2020-01-12 00:13:00,404  INFO "sessionId=7" WorldSessionActor - Hit: HitMessage(385,ValidPlanetSideGUID(40119),0,Some(HitInfo(Vector3(982.2031,1023.71875,100.890625),Vector3(983.7656,1022.2578,100.484375),Some(ValidPlanetSideGUID(7460)))),true,false,None)
2020-01-12 00:13:00,581  INFO "sessionId=7" WorldSessionActor - WeaponFire: WeaponFireMessage(389,ValidPlanetSideGUID(9829),ValidPlanetSideGUID(40120),Vector3(982.2031,1023.71875,100.890625),0,489,63583,200,255,0,None)
2020-01-12 00:13:00,581  INFO "sessionId=7" WorldSessionActor - Hit: HitMessage(389,ValidPlanetSideGUID(40120),0,Some(HitInfo(Vector3(982.2031,1023.71875,100.890625),Vector3(983.77344,1022.2578,100.484375),Some(ValidPlanetSideGUID(7460)))),true,false,None)
2020-01-12 00:13:00,756  INFO "sessionId=7" WorldSessionActor - WeaponFire: WeaponFireMessage(394,ValidPlanetSideGUID(9829),ValidPlanetSideGUID(40121),Vector3(982.2031,1023.71875,100.890625),0,497,63567,200,255,0,None)
2020-01-12 00:13:00,757  INFO "sessionId=7" WorldSessionActor - Hit: HitMessage(394,ValidPlanetSideGUID(40121),0,Some(HitInfo(Vector3(982.2031,1023.71875,100.890625),Vector3(983.7578,1022.25,100.484375),Some(ValidPlanetSideGUID(7460)))),true,false,None)
2020-01-12 00:13:00,911  INFO "sessionId=7" WorldSessionActor - WeaponFire: WeaponFireMessage(399,ValidPlanetSideGUID(9829),ValidPlanetSideGUID(40122),Vector3(982.2031,1023.71875,100.890625),0,483,63568,200,255,0,None)
2020-01-12 00:13:00,911  INFO "sessionId=7" WorldSessionActor - Hit: HitMessage(399,ValidPlanetSideGUID(40122),0,Some(HitInfo(Vector3(982.2031,1023.71875,100.890625),Vector3(983.7578,1022.2578,100.5),Some(ValidPlanetSideGUID(7460)))),true,false,None)
2020-01-12 00:13:01,073  INFO "sessionId=7" WorldSessionActor - WeaponFire: WeaponFireMessage(404,ValidPlanetSideGUID(9829),ValidPlanetSideGUID(40123),Vector3(982.2031,1023.71875,100.890625),0,490,63598,200,255,0,None)
2020-01-12 00:13:01,073  INFO "sessionId=7" WorldSessionActor - Hit: HitMessage(404,ValidPlanetSideGUID(40123),0,Some(HitInfo(Vector3(982.2031,1023.71875,100.890625),Vector3(983.78906,1022.2656,100.484375),Some(ValidPlanetSideGUID(7460)))),true,false,None)
2020-01-12 00:13:01,151  INFO "sessionId=7" WorldSessionActor - WeaponFire: WeaponFireMessage(409,ValidPlanetSideGUID(9829),ValidPlanetSideGUID(40124),Vector3(982.2031,1023.71875,100.890625),0,489,63560,200,255,0,None)
2020-01-12 00:13:01,248  INFO "sessionId=7" WorldSessionActor - Hit: HitMessage(409,ValidPlanetSideGUID(40124),0,Some(HitInfo(Vector3(982.2031,1023.71875,100.890625),Vector3(983.7578,1022.25,100.484375),Some(ValidPlanetSideGUID(7460)))),true,false,None)
2020-01-12 00:13:01,249 DEBUG "" services.support.SupportActor - a target submitted: Entry(net.psforever.objects.SensorDeployable@13e8b19d,Zones$$anon$14@12bb4822,0)
2020-01-12 00:13:01,267 DEBUG "" services.support.SupportActor - no tasks matching the targets List(net.psforever.objects.SensorDeployable@13e8b19d) have been cleared
2020-01-12 00:13:01,371  INFO "sessionId=7" WorldSessionActor - WeaponFire: WeaponFireMessage(414,ValidPlanetSideGUID(9829),ValidPlanetSideGUID(40100),Vector3(982.2031,1023.71875,100.890625),0,481,63550,200,255,0,None)
2020-01-12 00:13:01,371  INFO "sessionId=7" WorldSessionActor - Hit: HitMessage(414,ValidPlanetSideGUID(40100),0,Some(HitInfo(Vector3(982.2031,1023.71875,100.890625),Vector3(983.75,1022.2422,100.5),Some(ValidPlanetSideGUID(7460)))),true,false,None)
2020-01-12 00:13:01,376 ERROR "sourceThread=PsLogin-akka.actor.default-dispatcher-14, akkaSource=akka://PsLogin/user/world-udp-endpoint/world-session-router/world-session-7, sourceActorSystem=PsLogin, akkaTimestamp=00:13:01.374UTC" akka.actor.OneForOneStrategy - null
java.lang.NullPointerException: null
	at WorldSessionActor.HandleDealingDamage(WorldSessionActor.scala:8712)
	at WorldSessionActor.handleGamePkt(WorldSessionActor.scala:5661)
	at WorldSessionActor$$anonfun$Started$1.applyOrElse(WorldSessionActor.scala:359)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:482)
	at WorldSessionActor.akka$actor$MDCContextAware$$super$aroundReceive(WorldSessionActor.scala:80)
	at akka.actor.MDCContextAware$class.aroundReceive(MDCContextAware.scala:23)
	at WorldSessionActor.aroundReceive(WorldSessionActor.scala:80)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	```

**Comment by nwuollett** [comment]
This seems contained to ACE deployables when being destroyed with direct damage only (like using a Mini Chaingun).

**Comment by Fate-JH** [comment]
It's not the "killing" part that's causing the issue.  It's doing damage to their wreck after they are destroyed but before they are cleaned-up.  Specifically, damage being done in that period where the control agent of the deployable has been set back to "null."  The sensor deployables are most obvious in this case as, due to a code slip-up, destroying it normally incurs a 0s removal timer.  That's a perfect window to witness some disaster.

**Comment by NickPSF** [comment]
Issue no longer occurring
