### ISSUE TITLE
Non-unique actors are trying to be created

### ISSUE THREAD

**Issue by pschord** [psforever/PSF-LoginServer#325]
Not sure why this happens, but it occurs randomly when zoning. Seems like a race condition when switching zones.
https://github.com/psforever/PSF-LoginServer/blob/16c20eaeace747dfd30bf77a216b559eb4af9a20/common/src/main/scala/net/psforever/objects/zones/ZonePopulationActor.scala#L48

```
2020-01-12 01:27:09,338  INFO "sessionId=10" WorldSessionActor - Load in zone z4 at position Vector3(3059.0,2144.0,70.0) in 0 seconds
2020-01-12 01:27:09,338  INFO "sessionId=10" WorldSessionActor - Chat: ChatMsg(CMT_ZONE,true,,z4,None)
2020-01-12 01:27:09,338  INFO "" WorldSessionActor - Player asdf will respawn
2020-01-12 01:27:09,338  INFO "" WorldSessionActor - Setting up combat engineering UI ...
2020-01-12 01:27:09,339 ERROR "sourceThread=PsLogin-akka.actor.default-dispatcher-12, akkaSource=akka://PsLogin/user/service/cluster/z4-actor/z4-players, sourceActorSystem=PsLogin, akkaTimestamp=01:27:09.339UTC" akka.actor.OneForOneStrategy - actor name [asdf_3317] is not unique!
akka.actor.InvalidActorNameException: actor name [asdf_3317] is not unique!
	at akka.actor.dungeon.ChildrenContainer$NormalChildrenContainer.reserve(ChildrenContainer.scala:129)
	at akka.actor.dungeon.Children$class.reserveChild(Children.scala:130)
	at akka.actor.ActorCell.reserveChild(ActorCell.scala:374)
	at akka.actor.dungeon.Children$class.makeChild(Children.scala:268)
	at akka.actor.dungeon.Children$class.actorOf(Children.scala:42)
	at akka.actor.ActorCell.actorOf(ActorCell.scala:374)
	at net.psforever.objects.zones.ZonePopulationActor$$anonfun$receive$1.applyOrElse(ZonePopulationActor.scala:48)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:482)
	at net.psforever.objects.zones.ZonePopulationActor.aroundReceive(ZonePopulationActor.scala:21)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2020-01-12 01:27:09,750  INFO "sessionId=10" WorldSessionActor - CreateShortcutMessage: CreateShortcutMessage(ValidPlanetSideGUID(0),1,0,true,Some(Shortcut(0,medkit,,)))
2020-01-12 01:27:09,750  INFO "sessionId=10" WorldSessionActor - AvatarFirstTimeEvent: AvatarFirstTimeEventMessage(ValidPlanetSideGUID(3317),ValidPlanetSideGUID(6864),1,used_pulsar)
``

**Comment by Fate-JH** [comment]
Darn it, you still haven't updated this file!
