### ISSUE TITLE
Functionality - Zone Stability - Base Destruction - Spawn Tubes - When destroying a Facilities's Spawn Tubes, the owning Empire's players will fail to spawn at the next nearest Facility, despite having the Spawn Option, and zone objects and other functionality like player death will cease working and eventually lead to player disconnect.

### ISSUE THREAD

**Issue by NickPSF** [psforever/PSF-LoginServer#366]
When destroying a Facilities's Spawn Tubes, the owning Empire's players will fail to spawn at the next nearest Facility, despite having the Spawn Option, and zone objects and other functionality like player death will cease working and eventually lead to player disconnect.

`2020-04-17 19:09:16,006  INFO "sessionId=98" WorldSessionActor - SpawnRequestMessage: SpawnRequestMessage(0,Facility,0,0,6)
2020-04-17 19:09:16,009 ERROR "sourceThread=PsLogin-akka.actor.default-dispatcher-8, akkaSource=akka://PsLogin/user/service/cluster/z6-actor, sourceActorSystem=PsLogin, akkaTimestamp=19:09:16.008UTC" akka.actor.OneForOneStrategy - head of empty list
java.util.NoSuchElementException: head of empty list
    at scala.collection.immutable.Nil$.head(List.scala:420)
    at scala.collection.immutable.Nil$.head(List.scala:417)
    at net.psforever.objects.zones.ZoneActor$$anonfun$Processing$1.applyOrElse(ZoneActor.scala:93)
    at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
    at net.psforever.objects.zones.ZoneActor.aroundReceive(ZoneActor.scala:18)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
    at akka.actor.ActorCell.invoke(ActorCell.scala:495)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
    at akka.dispatch.Mailbox.run(Mailbox.scala:224)
    at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)`

**Comment by NickPSF** [comment]
Issue no longer occurring
