### ISSUE TITLE
Exploding many boomers causes a PacketCoding slot error

### ISSUE THREAD

**Issue by pschord** [psforever/PSF-LoginServer#432]
![image](https://user-images.githubusercontent.com/14133344/81868909-1b339680-9541-11ea-8e5a-7795c8a0aadf.png)

![image](https://user-images.githubusercontent.com/14133344/81870116-3b645500-9543-11ea-992d-8570d49d40ea.png)

```
2020-05-13 22:05:00,411  INFO "sessionId=405" WorldSessionActor - MoveItem: MoveItemMessage(ValidPlanetSideGUID(4417),ValidPlanetSideGUID(6972),ValidPlanetSideGUID(6972),250,1)
2020-05-13 22:05:00,425  INFO "sessionId=405" WorldSessionActor - MoveItem: jammer_grenade (mode=0-jammer_grenade_ammo)(3/3) moved from 1 to 250 in NC NCxRanger44 z3-6972 100/100 200/200
2020-05-13 22:05:00,586  INFO "sessionId=405" WorldSessionActor - DropItem: DropItemMessage(ValidPlanetSideGUID(4417))
2020-05-13 22:05:00,586  INFO "sessionId=405" WorldSessionActor - DropItem: DropItemMessage(ValidPlanetSideGUID(4417))
2020-05-13 22:05:00,586  WARN "" WorldSessionActor - DropItem: NC NCxRanger44 z3-6972 100/100 200/200 tried to drop a jammer_grenade (mode=0-jammer_grenade_ammo)(3/3) on the ground, but already dropped
2020-05-13 22:05:00,888  INFO "sessionId=421" WorldSessionActor - Splash: SplashHitMessage(673,ValidPlanetSideGUID(40117),Vector3(5005.0938,4285.5547,53.984375),39,0,Some(Vector3(84.4375,46.46875,-31.125)),None,
List(SplashedTarget(ValidPlanetSideGUID(9794),Vector3(5012.6953,4286.8047,54.0),65536,None)))
2020-05-13 22:05:00,942  INFO "sessionId=355" WorldSessionActor - MoveItem: MoveItemMessage(ValidPlanetSideGUID(9045),ValidPlanetSideGUID(7238),ValidPlanetSideGUID(7238),250,1)
2020-05-13 22:05:00,942  INFO "sessionId=355" WorldSessionActor - MoveItem: boomer_trigger moved from 42 to 250 in NC Hehateme1xandPutZx z3-7238 100/100 200/200
...
2020-05-13 22:05:13,006  INFO "sessionId=405" WorldSessionActor - Chat: ChatMsg(CMT_BROADCAST,true,,we doing boomer test,None)
...
2020-05-13 22:05:15,066  INFO "sessionId=405" WorldSessionActor - AvatarGrenadeStateMessage: AvatarGrenadeStateMessage(ValidPlanetSideGUID(6972),Primed)
...
2020-05-13 22:05:15,555  INFO "sessionId=405" WorldSessionActor - AvatarGrenadeStateMessage: AvatarGrenadeStateMessage(ValidPlanetSideGUID(6972),Thrown)
2020-05-13 22:05:15,555  INFO "sessionId=405" WorldSessionActor - WeaponFire: WeaponFireMessage(184,ValidPlanetSideGUID(9296),ValidPlanetSideGUID(40100),Vector3(4985.742,4368.367,46.265625),0,65361,4664,450,255,3,
Some(Some(Vector3(-4.59375,20.8125,1.4375))))
...
2020-05-13 22:05:15,960  INFO "" world-session-router - Dropping session ID=405 (reason: packet-session-405 died)
2020-05-13 22:05:15,961 ERROR "sourceThread=PsLogin-world-session-router-25, akkaSource=akka://PsLogin/user/world-udp-endpoint/world-session-router/packet-session-405, sourceActorSystem=PsLogin, akkaTimestamp=20:05:15.960UTC"
akka.actor.OneForOneStrategy - slot number is out of range - 4
java.lang.IllegalArgumentException: slot number is out of range - 4
|⋅⋅⋅⋅⋅⋅⋅at net.psforever.packet.control.RelatedB.<init>(RelatedB.scala:20)
|⋅⋅⋅⋅⋅⋅⋅at PacketCodingActor.handleControlPacket(PacketCodingActor.scala:365)
|⋅⋅⋅⋅⋅⋅⋅at PacketCodingActor.handlePacketContainer(PacketCodingActor.scala:345)
|⋅⋅⋅⋅⋅⋅⋅at PacketCodingActor.UnmarshalInnerPacket(PacketCodingActor.scala:327)
|⋅⋅⋅⋅⋅⋅⋅at PacketCodingActor$$anonfun$Established$1.applyOrElse(PacketCodingActor.scala:134)
|⋅⋅⋅⋅⋅⋅⋅at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
|⋅⋅⋅⋅⋅⋅⋅at PacketCodingActor.akka$actor$MDCContextAware$$super$aroundReceive(PacketCodingActor.scala:37)
|⋅⋅⋅⋅⋅⋅⋅at akka.actor.MDCContextAware$class.aroundReceive(MDCContextAware.scala:23)
|⋅⋅⋅⋅⋅⋅⋅at PacketCodingActor.aroundReceive(PacketCodingActor.scala:37)
|⋅⋅⋅⋅⋅⋅⋅at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
|⋅⋅⋅⋅⋅⋅⋅at akka.actor.ActorCell.invoke(ActorCell.scala:495)
|⋅⋅⋅⋅⋅⋅⋅at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
|⋅⋅⋅⋅⋅⋅⋅at akka.dispatch.Mailbox.run(Mailbox.scala:224)
|⋅⋅⋅⋅⋅⋅⋅at kamon.instrumentation.executor.ExecutorInstrumentation$InstrumentedForkJoinPool$TimingRunnable.run(ExecutorInstrumentation.scala:662)
|⋅⋅⋅⋅⋅⋅⋅at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:409)
|⋅⋅⋅⋅⋅⋅⋅at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
|⋅⋅⋅⋅⋅⋅⋅at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
|⋅⋅⋅⋅⋅⋅⋅at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
|⋅⋅⋅⋅⋅⋅⋅at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2020-05-13 22:05:15,961  INFO "" services.teamwork.SquadService - Actor[akka://PsLogin/user/world-udp-endpoint/world-session-router/world-session-405#-1759033803] has left /NC/Squad
2020-05-13 22:05:16,354 ERROR "sessionId=235" CryptoSessionActor - Could not decode raw packet: Unsupported packet type: ResetSequence
2020-05-13 22:05:16,450 DEBUG "" world-session-router - Reaped session ID=405
```

**Comment by Fate-JH** [comment]
We received that packet from the client.

Back in 68e3377 (the far distant past of March 2018), I rewrote `RelatedA` and `RelatedB` from their earlier variants, your `RelatedA0`, your `RelatedB0`, and your `SlottedMetaAck`.  `SlottedMetaAck` contained the following comment:
`//TODO 7 types of SlottedMeta, 4 types of ResultB?`
... and it did this to determine the opcode:
`val base = ControlPacketOpcode.RelatedB0.id`
`ControlPacketOpcode(base + slot % 4)`
Likewise, this comment read:
`// XXX: a nasty hack to ignore the "slot" field`
... and it so ignored the "slot" field using this trick:
`uint8L.xmap[Int](a => a - ControlPacketOpcode.RelatedB0.id, a=>a)`

Looking at `ControlPacketOpcode`, you'd realize that there were four varities of "RelatedA" packets and four varieties of "RelatedB" packets, each numbered from 0-3, but only the lowest numbers had decoders defined.  They were ordered by opcode as A0 A1 A2 A3 B0 B1 B2 B3.  `SlottedMetaAck` coerced slot information to transparently produce 1-3 of `ResultB0` (only `ResultB0`).  The data for creating the slot of the `RelatedB` that was fed into `SlottedMetaAck` came directly from an instigating `SlottedMetaPacket<slot>` packet.  While you technically could create a "ResultB4," you probably didn't want to.  "MultiPacketEx" is defined for that opcode (`0x19`).  `SlottedPacketAck` had a slot range of 0-7 but starting counting at `RelatedB0`, which meant it could also go beyond `MultiPacketEx` into unknown control packet types `0x1a` to `0x1c` when building this response packet.

When I rewrote the files, I got rid of `SlottedMetaAck` and worked its functionality into `RelatedA` and `RelatedB`.  The four different versions of each file seen in `ControlPacketOpcode` and originally only implied by the code that transformed the opcode could be constructed directly based on the slot field.  I borrowed the pattern that masked the opcode when producing the packet directly to allow the conversion when encoding or decoding.

So now we come down to the important question: "7 types of SlottedMeta, 4 types of ResultB?"

**Comment by Dethdeath** [comment]
Figured this could use an update as the server is completely different internally compared to 5 years ago.

A test with 75 boomers going off:

https://github.com/user-attachments/assets/971e6310-76ef-4b76-8990-826e036c171a

It caused a desync for 3 out of 4 players in the vicinity.

The only "surviving" player showed the aftermath:

<img width="1280" height="960" alt="Image" src="https://github.com/user-attachments/assets/d8e9f41c-1fc3-4c0a-a986-298684feaef0" />

The server had nothing to say about 75 boomers going off.

Another test, this time with 100 boomers:

https://github.com/user-attachments/assets/f2f9a3e5-4073-4cf1-94f1-db12a25df400

All 5 players desynced. The server also had this as the output:

<img width="1718" height="66" alt="Image" src="https://github.com/user-attachments/assets/8c1825a6-5410-47a8-92bb-3b247d145d7c" />

And nothing else besides that.

Conclusion: This issue isn't fully resolved yet and looks much different compared to before. I suppose players desyncing is bad but this is also an extreme circumstance. Maybe less info could be sent to each client at the same time to try and prevent the desync.

**Comment by Fate-JH** [comment]
Okay, since we've come back to this, all I can do as a proposed solution is direct out of bounds slot reconstruction to slot 0 always or map it over 0-3 again.
